### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by n05ucc4u** [hingston/7-billion-humans-solutions#115]
So I have a solution which only works on the old version, but is better than the current record, should i post it?

**Comment by hingston** [comment]
Sorry for the long reply. Which version does it work on?

**Comment by n05ucc4u** [comment]
before 16.09.2018 patch you didn't need to fill the very right column in checkerboard so i have a 36s solutuion

**Comment by n05ucc4u** [comment]
i also have a collation station 3s solution

**Comment by n05ucc4u** [comment]
oh wait

**Comment by n05ucc4u** [comment]
it actually works on the new version

**Comment by hingston** [comment]
Perfect, submit it and I will merge them all tonight. :)
