### ISSUE TITLE
Overview table and repository do not match

### ISSUE THREAD

**Issue by NeunEinser** [hingston/7-billion-humans-solutions#226]
99+%:

Year | Type | Fix
------------ | ------------- | -------------
12 | Size | Link should be https://github.com/hingston/7-billion-humans-solutions/blob/master/Solutions99%2B/Year%2012%20-%20Unzip%20(size).txt
12 | Speed | Link should be https://github.com/hingston/7-billion-humans-solutions/blob/master/Solutions99%2B/Year%2012%20-%20Unzip%20(speed).txt
23 | Speed | 2 times in repository, remove the one without txt ending
25 | Size | Table links to (speed).File with name (size) contains a better speed solution. Actual size solution is in the old commit: https://github.com/hingston/7-billion-humans-solutions/blob/7950ad05427f973a34f5b008fc48118b118a1253/Solutions99%2B/Year%2025%20-%20My%20First%20Shredding%20Memory%20(size).txt
25 | Speed | Table links to (size).
26 | Size | Link should be https://github.com/hingston/7-billion-humans-solutions/blob/master/Solutions99%2B/Year%2026%20-%20Budget%20Brigade%202%20(size).txt
26 | Speed | Link should be https://github.com/hingston/7-billion-humans-solutions/blob/master/Solutions99%2B/Year%2026%20-%20Budget%20Brigade%202%20(speed).txt
46 | Speed | Remove from repository (Both is avialable)
47 | Size | Rename file from (both) to (size) in repository.
47 | Speed | Size is not updated correctly.
48 | Both | Remove file from repository
48 | Size | Link should be https://github.com/hingston/7-billion-humans-solutions/blob/master/Solutions99%2B/Year%2048%20-%20Community%20Training%20Day%20(size)
48 | Speed | Link should be https://github.com/hingston/7-billion-humans-solutions/blob/master/Solutions99%2B/Year%2048%20-%20Community%20Training%20Day%20(speed)
56 | Speed | Link should be https://github.com/hingston/7-billion-humans-solutions/blob/master/Solutions99%2B/Year%2056%20-%20Local%20Maximums%20(speed).txt
65 | Size | Speed should be 369.
65 | Speed | Link should be https://github.com/hingston/7-billion-humans-solutions/blob/master/Solutions99%2B/Year%2065%20-%20Defrag%20Ordered%20(speed).txt

50+%:

Year | Type | Fix
------------ | ------------- | -------------
61 | Size | Does not appear in table, but file exists

<50%:

Year | Type | Fix
------------ | ------------- | -------------
22 | Both | Link should be https://github.com/hingston/7-billion-humans-solutions/blob/master/SolutionsLowPercent/Year%2022%20-%20Number%20Royale%20(both)
34 | Speed | Does not appear in table, but file exists
54 | Speed | Link should be https://github.com/hingston/7-billion-humans-solutions/blob/master/SolutionsLowPercent/Year%2054%20-%20Terrain%20Leveler%20(speed)
56 | Both | Does not appear in table, but file exists

**Comment by n05ucc4u** [comment]
also my first shredding memory has a speed solution instead of a size solution.

**Comment by NeunEinser** [comment]
Thank you, added Year 25.
Interestingly, the table links to the correct files, they are just both named the wrong way. So both the links in the table and the file names should change.

**Comment by n05ucc4u** [comment]
no, sorry for being unclear. file with the name SIZE contains a better SPEED solution, file with the name SPEED contains a worse SPEED solution, so no file contains SIZE solution.

**Comment by NeunEinser** [comment]
Right, size contains a 47 i 129 sec
Speed contains a 9 i 130 sec solution.

Size seems to be the file in the old commit: https://github.com/hingston/7-billion-humans-solutions/blob/6bdf96d2bc1cbc8a17dd02d7d486534d392b077c/Solutions99%2B/Year%2025%20-%20My%20First%20Shredding%20Memory%20(size).txt

Thanks for clearing this up.

**Comment by hingston** [comment]
@n05ucc4u @NeunEinser Everything should have been fixed in [here](https://github.com/hingston/7-billion-humans-solutions/commit/d8488942e295deba51e3e903114b484cd21e6446).
