### ISSUE TITLE
Impossible inputs

### ISSUE THREAD

**Issue by clonemeagain** [hingston/7-billion-humans-solutions#250]
https://github.com/hingston/7-billion-humans-solutions/blob/7685769c20b2b9416ea58208f2a481703a3dcb4e/Solutions99%2B/Year%2024%20-%20Budget%20Brigade%201%20(size).txt#L4

I get that multiple selections are possible later, but in year 24, they are one direction only. So I don't think this is the possible in-game.. you can paste this in, does that count?

**Comment by commonnickname** [comment]
Multiple selection isn't possible later either, but yes, the consensus seems to be that it counts if you can paste it in.

**Comment by clonemeagain** [comment]
Okay cool, Cheers

**Comment by gbolcer** [comment]
> 
> 
> Multiple selection isn't possible later either, but yes, the consensus seems to be that it counts if you can paste it in.

It's funny, I haven't been pasting them in as:
1) I thought you could only paste from other tabs, so didn't know pasting from an outside text was possible, and 
2) For (mostly) speed solutions, I wanted to solve them myself, and
3) For ones I did use the repo, I wanted to understand how the speed solution worked. 

I finished everything, but now I feel like I cheated!
